apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: litellm-db
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: ai-gateway
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: pg
      protocol: TCP
      name: pg
