apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  wait: true
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: litellm-provider-keys-vars
        optional: false
  dependsOn:
    - name: litellm-db
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./k8s/apps/litellm
